#' The CellScabbard class
#'
#' The main class used by the \pkg{BrainSABER} package to hold single cell 
#' expression data, relevant gene data, and similarity matrices.
#' CellScabbard extends the basic [Biobase::ExpressionSet-class] class.
#'
#' This class is initialized from a matrix of gene expression values and
#' associated metadata.  Methods that operate on CellScabbard objects
#' comprise the BrainSABER workflow.
#'
#'
#' @field relevantGenes A [Biobase::ExpressionSet-class] containing a
#'     subset of data from \pkg{AIBSARNA}. Generated by the \pkg{BrainSABER}
#'     workflow.
#' @field similarityScores  A \code{data.frame} containing similarity
#'     scores. Generated by the \pkg{BrainSABER} workflow.
#' @field similarityMatrices A [Biobase::AssayData-class] object containing
#'     similarity matrices, with identical dimensions, one for each sample in
#'     phenoData. Generated by the \pkg{BrainSABER} workflow.
#' @field UNDmatrices A [Biobase::AssayData-class] object containing
#'     identical-dimension UND matrices, one for each sample in phenoData.
#'     Generated by the \pkg{BrainSABER} workflow.
#' @name CellScabbard
#' @rdname CellScabbard
#' @aliases CellScabbard-class
#' @exportClass CellScabbard
#' @import Biobase
setClass( "CellScabbard",
          contains = "ExpressionSet",
          slots = c(relevantGenes = "ExpressionSet",
                    similarityScores = "data.frame",
                    similarityMatrices = "AssayData",
                    UNDmatrices = "AssayData"
          ),
          prototype = prototype( new( "VersionedBiobase",
                                    versions = c(
                                      Biobase::classVersion("ExpressionSet"),
                                      CellScabbard = "0.1.0" ) ))
)
